services:
  frontend:
    container_name: frontend_c
    build:
      context: frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    networks:
      - app-network

  backend:
    container_name: backend_c
    build:
      context: backend
    ports:
      - "8081:8081"
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: YouAreNotHere
      DB_PASSWORD: 123456
      DB_NAME: app_db
    restart: on-failure
    networks:
      - app-network

  db:
    image: mysql:8.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: app_db
      MYSQL_USER: YouAreNotHere
      MYSQL_PASSWORD: 123456
      MYSQL_DISABLE_SSL: 1  # Отключаем SSL для WSL2
    volumes:
      - mysql_data:/var/lib/mysql  # Используем named volume
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -uroot -p123456" ]
      interval: 20s
      timeout: 10s
      retries: 30
    networks:
      - app-network

volumes:
  mysql_data:  # Объявляем named volume для MySQL

networks:
  app-network:
    driver: bridge