version: '3.8'

services:
  frontend:
    container_name: frontend_c
    build:
      context: frontend
    ports:
      - "5173:5173"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"

  backend:
    container_name: backend_c
    build:
      context: backend
    ports:
      - "8081:8081"
    volumes:
      - "./backend:/app"
      - "/app/node_modules"
      - "./uploads:/app/uploads"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306

  db:
    image: mysql:8.4
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test_db
      MYSQL_USER: YouAreNotHere
      MYSQL_PASSWORD: 123456
    volumes:
      - /tmp/dbdata:/var/lib/mysql
#      - ./mysql-config:/etc/mysql/conf.d
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -uYouAreNotHere -p123456" ]
      interval: 10s
      timeout: 5s
      retries: 20